#Q3. List the USER_ID, FNAME, LNAME of female mutual friends between users 1 and 2.
SELECT F.UID, USERS.FNAME, USERS.LNAME FROM (
	SELECT F1.UID FROM 
		(SELECT INVITER_ID AS UID FROM FRIENDSHIPS WHERE INVITEE_ID = 1
			UNION 
			SELECT INVITEE_ID AS UID FROM FRIENDSHIPS WHERE INVITER_ID=1) AS F1
		INNER JOIN
		(SELECT INVITER_ID AS UID FROM FRIENDSHIPS WHERE INVITEE_ID = 2
			UNION 
			SELECT INVITEE_ID AS UID FROM FRIENDSHIPS WHERE INVITER_ID=2) AS F2
		ON F1.UID = F2.UID
) AS F INNER JOIN USERS ON F.UID = USERS.USER_ID
WHERE USERS.GENDER = 'F';