#Q4. List the USER_ID of female users who were born after ‘1990-12-20’ and commented on posts of
#		 USER_ID=10. Show their friends count in a separate column.
SELECT U.USER_ID, COUNT(F.FRIENDS)
FROM 
(SELECT USER_ID
   FROM USERS
   WHERE GENDER = 'F' AND DATE_OF_BIRTH > '1990-12-20' AND USER_ID IN (
      SELECT USER_ID  FROM COMMENTS 
	  WHERE POST_ID IN (SELECT POST_ID FROM POSTS WHERE USER_ID = 10)
	)
) AS U 
INNER JOIN 
(SELECT DISTINCT(F1.USER_ID), F1.FRIENDS FROM 
   (SELECT INVITER_ID AS USER_ID, INVITEE_ID AS FRIENDS FROM FRIENDSHIPS WHERE STATUS = 1
   UNION
   SELECT INVITEE_ID AS USER_ID, INVITER_ID AS FRIENDS FROM FRIENDSHIPS WHERE STATUS = 1
	) AS F1
) AS F
ON U.USER_ID = F.USER_ID
GROUP BY U.USER_ID;