#Q6. List the user ids of up to 10 pairs of users where one is male and the other is female, and each
#		 comments on the other’s posts at least 5 times. 
SELECT DISTINCT(RESULT1.BEST_FRIEND_1), RESULT1.BEST_FRIEND_2
FROM (
	SELECT BF_PAIR.COMMENTER AS BEST_FRIEND_1, BF_PAIR.POSTER AS BEST_FRIEND_2
	FROM USERS AS U1, USERS AS U2,
	(
		SELECT BF1.COMMENTER, BF1.POSTER
		FROM
		(SELECT COM.USER_ID AS COMMENTER,  P.USER_ID AS POSTER
				FROM COMMENTS AS COM, POSTS AS P
				WHERE COM.POST_ID = P.POST_ID
				GROUP BY COM.POST_ID, COM.USER_ID
				HAVING COUNT(COM.COMMENT_ID) >= 5) AS BF1
		  INNER JOIN
          (SELECT P.USER_ID AS COMMENTER,  COM.USER_ID AS POSTER
				FROM COMMENTS AS COM, POSTS AS P
				WHERE COM.POST_ID = P.POST_ID
				GROUP BY COM.POST_ID, COM.USER_ID
				HAVING COUNT(COM.COMMENT_ID) >= 5) AS BF2
		  ON BF1.COMMENTER = BF2.COMMENTER AND BF1.POSTER = BF2.POSTER
	) AS BF_PAIR
	WHERE BF_PAIR.COMMENTER = U1.USER_ID AND BF_PAIR.POSTER = U2.USER_ID
	AND U1.GENDER <> U2.GENDER) AS RESULT1 
LEFT JOIN 
    (
	SELECT BF_PAIR.COMMENTER AS BEST_FRIEND_1, BF_PAIR.POSTER AS BEST_FRIEND_2
	FROM USERS AS U1, USERS AS U2,
	(
		SELECT BF1.COMMENTER, BF1.POSTER
		FROM
		(SELECT COM.USER_ID AS COMMENTER,  P.USER_ID AS POSTER
				FROM COMMENTS AS COM, POSTS AS P
				WHERE COM.POST_ID = P.POST_ID
				GROUP BY COM.POST_ID, COM.USER_ID
				HAVING COUNT(COM.COMMENT_ID) >= 5) AS BF1
		  INNER JOIN
          (SELECT P.USER_ID AS COMMENTER,  COM.USER_ID AS POSTER
				FROM COMMENTS AS COM, POSTS AS P
				WHERE COM.POST_ID = P.POST_ID
				GROUP BY COM.POST_ID, COM.USER_ID
				HAVING COUNT(COM.COMMENT_ID) >= 5) AS BF2
		  ON BF1.COMMENTER = BF2.COMMENTER AND BF1.POSTER = BF2.POSTER
	) AS BF_PAIR
	WHERE BF_PAIR.COMMENTER = U1.USER_ID AND BF_PAIR.POSTER = U2.USER_ID
	AND U1.GENDER <> U2.GENDER) AS RESULT2
ON RESULT1.BEST_FRIEND_1 = RESULT2.BEST_FRIEND_2 AND RESULT1.BEST_FRIEND_2 = RESULT2.BEST_FRIEND_1
WHERE RESULT1.BEST_FRIEND_1 < RESULT2.BEST_FRIEND_1 OR RESULT2.BEST_FRIEND_1 IS NULL
LIMIT 10;
